apiVersion: batch/v1
kind: Job
metadata:
  name: s3-list
  namespace: infrastructure
  labels:
    app: s3-list
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/name: s3-list
    spec:
      containers:
        - name: s3-list
          image: amazon/aws-cli
          imagePullPolicy: Always
          args: ["s3", "ls"]
      restartPolicy: Never
      serviceAccountName: eks-s3
  backoffLimit: 1