apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: auto-ebs-sc
provisioner: ebs.csi.eks.amazonaws.com
parameters:
  type: gp2
  encrypted: "true"
  kmsKeyId: arn:aws:kms:us-west-2:123456789012:key/1234abcd-12ab-34cd-56ef-1234567890ab
  iopsPerGB: "10"
  fsType: ext4
  volumeBindingMode: WaitForFirstConsumer
  allowVolumeExpansion: true
reclaimPolicy: Retain